In [2]:
import pandas as pd

path = "data/yellow_tripdata_2023-01.parquet"
df = pd.read_parquet(path)

df.head()

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,airport_fee
0,2,2023-01-01 00:32:10,2023-01-01 00:40:36,1.0,0.97,1.0,N,161,141,2,9.3,1.00,0.5,0.00,0.0,1.0,14.30,2.5,0.00
1,2,2023-01-01 00:55:08,2023-01-01 01:01:27,1.0,1.10,1.0,N,43,237,1,7.9,1.00,0.5,4.00,0.0,1.0,16.90,2.5,0.00
2,2,2023-01-01 00:25:04,2023-01-01 00:37:49,1.0,2.51,1.0,N,48,238,1,14.9,1.00,0.5,15.00,0.0,1.0,34.90,2.5,0.00
3,1,2023-01-01 00:03:48,2023-01-01 00:13:25,0.0,1.90,1.0,N,138,7,1,12.1,7.25,0.5,0.00,0.0,1.0,20.85,0.0,1.25
4,2,2023-01-01 00:10:29,2023-01-01 00:21:19,1.0,1.43,1.0,N,107,79,1,11.4,1.00,0.5,3.28,0.0,1.0,19.68,2.5,0.00

In [3]:
df.shape

(3066766, 19)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3066766 entries, 0 to 3066765
Data columns (total 19 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int64
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     object
 7   PULocationID           int64
 8   DOLocationID           int64
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  airport_fee            float64
dtypes: datetime64[us](2), float64(12), int64(4), object(1)
memory usage: 444.6+ MB

In [5]:
df.isnull().sum()

VendorID                     0
tpep_pickup_datetime         0
tpep_dropoff_datetime        0
passenger_count          71743
trip_distance                0
RatecodeID               71743
store_and_fwd_flag       71743
PULocationID                 0
DOLocationID                 0
payment_type                 0
fare_amount                  0
extra                        0
mta_tax                      0
tip_amount                   0
tolls_amount                 0
improvement_surcharge        0
total_amount                 0
congestion_surcharge     71743
airport_fee              71743
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
cols_to_keep = ["tpep_pickup_datetime", "PULocationID", "trip_distance"]

In [8]:
df=df[cols_to_keep]

In [9]:
df

        tpep_pickup_datetime  PULocationID  trip_distance
0        2023-01-01 00:32:10           161           0.97
1        2023-01-01 00:55:08            43           1.10
2        2023-01-01 00:25:04            48           2.51
3        2023-01-01 00:03:48           138           1.90
4        2023-01-01 00:10:29           107           1.43
...                      ...           ...            ...
3066761  2023-01-31 23:58:34           107           3.05
3066762  2023-01-31 23:31:09           112           5.80
3066763  2023-01-31 23:01:05           114           4.67
3066764  2023-01-31 23:40:00           230           3.15
3066765  2023-01-31 23:07:32           262           2.85

[3066766 rows x 3 columns]

In [10]:
df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")

C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\299934099.py:1: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")

In [11]:
hourly_demand = df.groupby(["hour", "PULocationID"]).size().reset_index(name="demand")

In [12]:
df

        tpep_pickup_datetime  PULocationID  trip_distance                hour
0        2023-01-01 00:32:10           161           0.97 2023-01-01 00:00:00
1        2023-01-01 00:55:08            43           1.10 2023-01-01 00:00:00
2        2023-01-01 00:25:04            48           2.51 2023-01-01 00:00:00
3        2023-01-01 00:03:48           138           1.90 2023-01-01 00:00:00
4        2023-01-01 00:10:29           107           1.43 2023-01-01 00:00:00
...                      ...           ...            ...                 ...
3066761  2023-01-31 23:58:34           107           3.05 2023-01-31 23:00:00
3066762  2023-01-31 23:31:09           112           5.80 2023-01-31 23:00:00
3066763  2023-01-31 23:01:05           114           4.67 2023-01-31 23:00:00
3066764  2023-01-31 23:40:00           230           3.15 2023-01-31 23:00:00
3066765  2023-01-31 23:07:32           262           2.85 2023-01-31 23:00:00

[3066766 rows x 4 columns]

In [13]:
hourly_demand = hourly_demand.sort_values(["PULocationID", "hour"])

In [14]:
df

        tpep_pickup_datetime  PULocationID  trip_distance                hour
0        2023-01-01 00:32:10           161           0.97 2023-01-01 00:00:00
1        2023-01-01 00:55:08            43           1.10 2023-01-01 00:00:00
2        2023-01-01 00:25:04            48           2.51 2023-01-01 00:00:00
3        2023-01-01 00:03:48           138           1.90 2023-01-01 00:00:00
4        2023-01-01 00:10:29           107           1.43 2023-01-01 00:00:00
...                      ...           ...            ...                 ...
3066761  2023-01-31 23:58:34           107           3.05 2023-01-31 23:00:00
3066762  2023-01-31 23:31:09           112           5.80 2023-01-31 23:00:00
3066763  2023-01-31 23:01:05           114           4.67 2023-01-31 23:00:00
3066764  2023-01-31 23:40:00           230           3.15 2023-01-31 23:00:00
3066765  2023-01-31 23:07:32           262           2.85 2023-01-31 23:00:00

[3066766 rows x 4 columns]

In [15]:
hourly_demand

                     hour  PULocationID  demand
2     2022-10-24 17:00:00             1       1
8     2022-10-25 03:00:00             1       1
623   2023-01-01 05:00:00             1       1
916   2023-01-01 08:00:00             1       1
1224  2023-01-01 11:00:00             1       1
...                   ...           ...     ...
71170 2023-01-31 19:00:00           265       2
71264 2023-01-31 20:00:00           265       1
71352 2023-01-31 21:00:00           265       3
71439 2023-01-31 22:00:00           265       5
71525 2023-01-31 23:00:00           265       5

[71534 rows x 3 columns]

In [16]:
hourly_demand['demand'].mean()

np.float64(42.87144574607879)

In [ ]:
class HourlyDemandDataset:
    def __init__(self, path):
        self.path = path

    def load_data(self):
        df = pd.read_parquet(self.path)

        # Keep only necessary columns
        df = df[["tpep_pickup_datetime", "PULocationID"]]

        # Ensure datetime format
        df["tpep_pickup_datetime"] = pd.to_datetime(df["tpep_pickup_datetime"])

        # Extract hourly timestamp
        df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")

        # Compute demand per hour per zone
        hourly = df.groupby(["hour", "PULocationID"]).size().reset_index(name="demand")

        # Sort for lag features
        hourly = hourly.sort_values(["PULocationID", "hour"]).reset_index(drop=True)

        return hourly

In [54]:

def build_full_grid(hourly):
    all_hours = pd.date_range(start=hourly["hour"].min(),
                              end=hourly["hour"].max(),
                              freq='H')
    all_zones = hourly["PULocationID"].unique()

    full_index = pd.MultiIndex.from_product(
        [all_hours, all_zones],
        names=["hour", "PULocationID"]
    )

    full_df = full_index.to_frame().reset_index(drop=True)

    full_df = full_df.merge(hourly, on=["hour", "PULocationID"], how="left")
    full_df["demand"] = full_df["demand"].fillna(0)

    return full_df

In [48]:
file_paths = [
    "data/yellow_tripdata_2023-01.parquet",
    "data/yellow_tripdata_2023-02.parquet",
    "data/yellow_tripdata_2023-03.parquet",
    "data/yellow_tripdata_2023-04.parquet",
    "data/yellow_tripdata_2023-05.parquet",
    "data/yellow_tripdata_2023-06.parquet",
    "data/yellow_tripdata_2023-07.parquet",
    "data/yellow_tripdata_2023-08.parquet",
    "data/yellow_tripdata_2023-09.parquet",
    "data/yellow_tripdata_2023-10.parquet",
    "data/yellow_tripdata_2023-11.parquet",
    "data/yellow_tripdata_2023-12.parquet"
]


all_monthly_hourly = []

for path in file_paths:
    dataset = HourlyDemandDataset(path)
    hourly_df = dataset.load_data()
    all_monthly_hourly.append(hourly_df)

# Combine all months
hourly_demand_all = pd.concat(all_monthly_hourly, ignore_index=True)

# ---- FIX: FILTER ONLY 2023 ----
hourly_demand_all = hourly_demand_all[
    hourly_demand_all['hour'].dt.year == 2023
]

# Re-group AFTER filtering
hourly_demand_all = (
    hourly_demand_all.groupby(["hour", "PULocationID"], as_index=False)
                     .agg({"demand": "sum"})
                     .sort_values(["PULocationID", "hour"])
                     .reset_index(drop=True)
)

print("Unique hours:", hourly_demand_all['hour'].nunique())
print("Row count before building grid:", hourly_demand_all.shape)

C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")
C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\1996908061.py:15: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  df["hour"] = df["tpep_pickup_datetime"].dt.floor("H")

Unique hours: 8759
Row count before building grid: (886277, 3)

In [70]:

full_grid_ = build_full_grid(hourly_demand_all)
print(full_grid_.shape)

C:\Users\Pawan\AppData\Local\Temp\ipykernel_19104\2668871907.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  all_hours = pd.date_range(start=hourly["hour"].min(),

(2303880, 3)

In [73]:
import os
save_path = os.path.join("data", "full_hourly_demand_2023.csv")


full_grid_.to_csv(save_path, index=False)

print("Saved to:", save_path)

Saved to: data\full_hourly_demand_2023.csv

In [56]:
def add_lag_features(df):
    df = df.sort_values(["PULocationID", "hour"]).reset_index(drop=True)

    df["lag_1"] = df.groupby("PULocationID")["demand"].shift(1)
    df["lag_24"] = df.groupby("PULocationID")["demand"].shift(24)
    df["lag_168"] = df.groupby("PULocationID")["demand"].shift(168)

    return df

In [58]:
full_grid.head()

                 hour  PULocationID  demand  lag_1  lag_24  lag_168
0 2023-01-01 00:00:00             1     0.0    NaN     NaN      NaN
1 2023-01-01 01:00:00             1     0.0    0.0     NaN      NaN
2 2023-01-01 02:00:00             1     0.0    0.0     NaN      NaN
3 2023-01-01 03:00:00             1     0.0    0.0     NaN      NaN
4 2023-01-01 04:00:00             1     0.0    0.0     NaN      NaN

In [59]:
full_grid.shape

(2303880, 6)

In [60]:
full_grid.isnull().sum()

hour                0
PULocationID        0
demand              0
lag_1             263
lag_24           6312
lag_168         44184
dtype: int64

In [63]:
df=full_grid
df.dropna(inplace=True)

In [64]:
df.isnull().sum()

hour            0
PULocationID    0
demand          0
lag_1           0
lag_24          0
lag_168         0
dtype: int64

In [65]:
df.head()

                   hour  PULocationID  demand  lag_1  lag_24  lag_168
168 2023-01-08 00:00:00             1     0.0    0.0     0.0      0.0
169 2023-01-08 01:00:00             1     0.0    0.0     0.0      0.0
170 2023-01-08 02:00:00             1     0.0    0.0     0.0      0.0
171 2023-01-08 03:00:00             1     0.0    0.0     0.0      0.0
172 2023-01-08 04:00:00             1     0.0    0.0     0.0      0.0

In [67]:
import numpy as np
import pandas as pd
from pandas.tseries.holiday import USFederalHolidayCalendar

def build_features(df):
    """
    Input df must contain:
    - hour (datetime)
    - PULocationID
    - demand
    - lag_1, lag_24, lag_168
    - cluster_id
    """

    # ---------- BASIC TIME FEATURES ----------
    df["hour_of_day"] = df["hour"].dt.hour
    df["day_of_week"] = df["hour"].dt.dayofweek
    df["day_of_month"] = df["hour"].dt.day
    df["month"] = df["hour"].dt.month

    # ---------- FLAGS ----------
    df["is_weekend"] = df["day_of_week"].isin([5, 6]).astype(int)
    df["is_peak_hour"] = df["hour_of_day"].isin([7, 8, 9, 16, 17, 18]).astype(int)

    # ---------- CYCLICAL ENCODING ----------
    df["hour_sin"] = np.sin(2 * np.pi * df["hour_of_day"] / 24)
    df["hour_cos"] = np.cos(2 * np.pi * df["hour_of_day"] / 24)

    df["dow_sin"] = np.sin(2 * np.pi * df["day_of_week"] / 7)
    df["dow_cos"] = np.cos(2 * np.pi * df["day_of_week"] / 7)

    # ---------- HOLIDAY FEATURE ----------
    cal = USFederalHolidayCalendar()
    holidays = cal.holidays(
        start=df["hour"].min(),
        end=df["hour"].max()
    )

    df["is_holiday"] = df["hour"].dt.normalize().isin(holidays).astype(int)

    # ---------- LOG TRANSFORM (CRITICAL) ----------
    for col in ["demand", "lag_1", "lag_24", "lag_168"]:
        df[col] = np.log1p(df[col])

    # ---------- DROP RAW TIMESTAMP ----------
    df = df.drop(columns=["hour"])

    return df

In [68]:
train_df = build_features(df)

In [69]:
train_df.head()

,PULocationID,demand,lag_1,lag_24,lag_168,hour_of_day,day_of_week,day_of_month,month,is_weekend,is_peak_hour,hour_sin,hour_cos,dow_sin,dow_cos,is_holiday
168,1,0.0,0.0,0.0,0.0,0,6,8,1,1,0,0.000000,1.000000,-0.781831,0.62349,0
169,1,0.0,0.0,0.0,0.0,1,6,8,1,1,0,0.258819,0.965926,-0.781831,0.62349,0
170,1,0.0,0.0,0.0,0.0,2,6,8,1,1,0,0.500000,0.866025,-0.781831,0.62349,0
171,1,0.0,0.0,0.0,0.0,3,6,8,1,1,0,0.707107,0.707107,-0.781831,0.62349,0
172,1,0.0,0.0,0.0,0.0,4,6,8,1,1,0,0.866025,0.500000,-0.781831,0.62349,0